<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_-</name>
   <tag></tag>
   <elementGuidId>2b45272e-a46c-490b-bc94-967f0ca35f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col > form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>3f318faa-6b8f-4bd5-9523-260a1efc2075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน</value>
      <webElementGuid>2c2f062b-f14d-418c-94ba-e057ccc1727e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/form[1]</value>
      <webElementGuid>7742b0e3-1213-413f-8ae7-8bb9c9e70a48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='']</value>
      <webElementGuid>da6892a3-4003-4f46-9ce9-dad22d734d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form</value>
      <webElementGuid>898a9f76-1289-4f55-bb14-22713c5347c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชั้นปี'])[1]/following::form[1]</value>
      <webElementGuid>6d1df74d-3f18-4614-921e-e0712c0b0a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสนิสิต'])[1]/following::form[1]</value>
      <webElementGuid>282b4311-0d87-4398-9bbf-63a37d8881b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form</value>
      <webElementGuid>57d24bc8-a6ca-4ef9-95ec-f547e29b6634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน' or . = 'แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน')]</value>
      <webElementGuid>7495c280-5e36-41d6-ad6e-7717154b276e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
