<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_-</name>
   <tag></tag>
   <elementGuidId>6aa77258-77b7-43e2-8a6e-c980a29591f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col > form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d7d84a8e-e889-4aac-b933-48864f2cfdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน</value>
      <webElementGuid>4b871c88-aa5f-41a3-82bf-d458d04d26d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/form[1]</value>
      <webElementGuid>e46738ce-a1ee-4d4e-b648-b188a9328996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='']</value>
      <webElementGuid>96735d4d-74b1-47ec-9af9-1179188f19e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form</value>
      <webElementGuid>4e1beb23-ddda-41a8-ad12-92126f2e4aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชั้นปี'])[1]/following::form[1]</value>
      <webElementGuid>e5d4efe5-6179-47be-8032-03345ff200ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสนิสิต'])[1]/following::form[1]</value>
      <webElementGuid>9bdb42d8-a6a6-4fec-8606-b0cf3f38eba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form</value>
      <webElementGuid>11b1a0a7-ada5-4a3c-80a8-478fc4af94a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน' or . = 'แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน')]</value>
      <webElementGuid>999eaff5-3304-42f9-8ba2-2cb1bd47da73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
